### ISSUE TITLE
Upload it to Pypi

### ISSUE THREAD

**Issue by reiinakano** [ajbouh/tfi#1]
I don't really use TF but this seems useful. I just noticed that it's not in Pypi yet. You should really add it in there so people can do `pip install tfi` instead of having to clone.

**Comment by ajbouh** [comment]
Good idea. Is there a particular model you'd like to use it with? I want to
improve its test coverage.

Will follow up here once it's posted on pypi

**Comment by ajbouh** [comment]
It should now be installable via `pip install tfi`

Please open a followup issue with for any models you think are worth adding test coverage for.

Thanks again for the suggestion!
