### ISSUE TITLE
readme - updates

### ISSUE THREAD

**Issue by johndpope** [ajbouh/tfi#3]
https://github.com/ajbouh/tfi/blob/2df839122580a0583ee065f1b52e9db08e547415/README.rst

for some reason the code below 

code-block:: bash

   $ git clone https://github.com/tensorflow/models
   $ export PYTHONPATH=$PWD/models/slim

is hidden on chrome browser. 
eg.
code-block:: python
   from datasets import dataset_factory
   from nets import nets_factory
   import os.path
   import tensorflow as tf
   import tfi
   from urllib.request import urlretrieve

<img width="953" alt="screen shot 2017-09-25 at 3 05 26 pm" src="https://user-images.githubusercontent.com/289994/30826046-020c0590-a203-11e7-9f2f-a073abf232f5.png">

maybe more appropriate to use a gist
https://gist.github.com/johndpope/305cf2c96db581123e878b7e17c4efa5

**Comment by ajbouh** [comment]
Fixed in master and based on your suggestion I've also added link to a gist I prepared a few days ago.

Thanks for the bug report!

**Comment by ajbouh** [comment]
Please reopen if you think this hasn't been resolved
